### ISSUE TITLE
New repo: Pirates of the Spanish Main by Wizkids

### ISSUE THREAD

**Issue by HappyWeasel** [BSData/catalogue-development#105]
Hey I was wondering if you would be interested in hosting a data base for the tcg/miniature war game based on battling with large fleets of small cardboard ships. I have all the data in a spreadsheet and rules doc. The game ran in the early 2000s and now is becoming more and more rare. I think it would be cool to have  virtual version for home brews or people trying to bring it back. Let me know what you think.

HappyWeasel (Jericho)

**Comment by Mad-Spy** [comment]
In order to host on BSData, you will first need to create data files for the game system. Joining the Data Authors Discord, and looking at existing files is the best way to learn how to create data files for Battlescribe.

[![Chat on Discord](https://img.shields.io/discord/558412685981777922.svg?logo=discord&style=popout-square)](https://discord.gg/KqPVhds)

Once you've created your data files, open a new issue here to request that it be added.
