### ISSUE TITLE
New repo:New World

### ISSUE THREAD

**Issue by Nazgul20** [BSData/catalogue-development#109]

**Comment by Mad-Spy** [comment]
In order to host on BSData, you will first need to create data files for the game system. Joining the Data Authors Discord, and looking at existing files is the best way to learn how to create data files for Battlescribe.

[![Chat on Discord](https://img.shields.io/discord/558412685981777922.svg?logo=discord&style=popout-square)](https://discord.gg/KqPVhds)

Once you've created your data files, open a new issue here to request that it be added, including a link to the repo containing your data files.
