### ISSUE TITLE
New repo: Blood & Valor

### ISSUE THREAD

**Issue by Shannegh** [BSData/catalogue-development#112]
Battlescribe repository for Blood & Valor game system.

**Comment by Shannegh** [comment]
Apologies for lack of familiarity with the Github system. I created gstz and catz for a new game system, Blood & Valor, and am having a hard time figuring out how to get them uploaded and presentable here. Would appreciate assistance.

**Comment by Shannegh** [comment]
https://github.com/Shannegh/Blood-Valor

**Comment by Mad-Spy** [comment]
The repo above is not public, so we can't see it. You should upload the unzipped GST and CAT files, rather than the zipped versions, as it allows Github's versioning to work correctly.

 Joining the Data Authors Discord, and looking at existing files is the best way to learn how to create data files for Battlescribe.

[![Chat on Discord](https://img.shields.io/discord/558412685981777922.svg?logo=discord&style=popout-square)](https://discord.gg/KqPVhds)

**Comment by Shannegh** [comment]
Made the repo public. Have the CAT and GST files on there.

**Comment by Mad-Spy** [comment]
.approve

**Comment by Mad-Spy** [comment]
You do not need to upload the catz or gstz when you add your files to the new repo.

**Comment by Mad-Spy** [comment]
Please upload your files to the new repository as soon as possible. 
Empty repositories will be deleted after 1 month.
