### ISSUE TITLE
New repo: Mortal Gods

### ISSUE THREAD

**Issue by JohnnyTSpark** [BSData/catalogue-development#116]
Hello there! I'm a complete newcomer to this, but wanted to use the Mortal Gods game system as a way to learn BattleScribe. Any help will be much appreciated! I'm working my way through the various help documentation that's available here.

**Comment by Mad-Spy** [comment]
In order to host on BSData, you will first need to create data files for the game system. Joining the Data Authors Discord, and looking at existing files is the best way to learn how to create data files for Battlescribe.

[![Chat on Discord](https://img.shields.io/discord/558412685981777922.svg?logo=discord&style=popout-square)](https://discord.gg/KqPVhds)

Once you've created your data files, open a new issue here to request that it be added.
