### ISSUE TITLE
Adding a game?

### ISSUE THREAD

**Issue by peterlyberth** [BSData/catalogue-development#14]
I am so sorry if I am asking a stupid question or asking the wrong place, but here goes.

I am working a a complete set of files for the 15 mm game Patrol Angis. I have two forced so far. My question ism how do I add it to bsdata?

**Comment by amis92** [comment]
Hi @peterlyberth,

In general, if you want to provide new game system's files, the procedure is as follows:
1. I create new repository for given game system (https://github.com/BSData/patrol-angis)
2. I give you push/write access to this new repository
3. You upload files and maintain them if possible.

The important part is that we Organization Admins do not have time to maintain/push/upload files. So unless there is someone else interested, you'll have to do some work to make our website host those files.

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

**Please read carefully**:
As this is a new repository, please read Developer Guide linked above very carefully. For example, save all files in unzipped format (`.cat` instead of `.catz` and `.gst` instead of `.gstz`); you can achieve this using `File`->`Save as` and choosing the correct format from dropdown under filename.
You also shouldn't put in any index files (`index.xml` or `index.bsi`), the website on AppSpot does indexing automatically.

Cheers!
Amis

PS You can always `@mention` me by writing `@amis92` in your issue comment, and I'll try to help you out.
