### ISSUE TITLE
New repo: Edge: Dawnfall

### ISSUE THREAD

**Issue by Blackfire0** [BSData/catalogue-development#141]
What we need to get started?

**Comment by Mad-Spy** [comment]
Where are you starting from? Have you read the wiki articles? Started writing data files?

**Comment by Blackfire0** [comment]
Yes, read and now working on data files.

**Comment by Mad-Spy** [comment]
I'd also suggest joining the Data Authors Discord, if you haven't already.

**Comment by Blackfire0** [comment]
I'm done with the data: [GitHub](https://github.com/Blackfire0/EdgeDawnfall)

However, there is a problem: When I start the program, it automatically moves 3 catalogues to the backup directory in each case. No error message.

**Comment by Blackfire0** [comment]
I think he’s been doing this since I copy and paste entry from one catalog to another.

**Comment by Mad-Spy** [comment]
@Blackfire0 This normally happens because the version of the data file is different to the version of the data editor. BS will automatically upgrade them when you open the editor, and creates a backup of the old one.

Once you've saved a version which matches, they'll stop getting created.

**Comment by Blackfire0** [comment]
But at the same time I create everything, fresh installation, can not be different version. 
In all cataloge file: battleScribeVersion = "2.03"

And it doesn't make a copy to backup folder, it deletes the original catalogue file.

**Comment by Mad-Spy** [comment]
@Blackfire0 I've found the problem. The catalogue IDs for the ones that get deleted are the same, so BS deletes them as duplicates. You need to go through and regenerate them so they are all unique.

Also, you'll have problems with anyone who uses profile summaries, because many of your Profiles are named "Profile". BS collapses by name, so the output would only ever show one.

![image](https://user-images.githubusercontent.com/29306451/95879253-0ec09d80-0d6e-11eb-9f97-be00ae9c4075.png)

**Comment by Blackfire0** [comment]
@Mad-Spy Thank you very much for your help, it now works! Then I'm done, I've uploaded everything to the github.
