### ISSUE TITLE
New repo: wh40k - Fundapocalypse

### ISSUE THREAD

**Issue by normanthesquid** [BSData/catalogue-development#155]
My gaming group (Fundamalleus, hence the name) is working on building new profiles for units that have been added to 40k since Apocalypse does not appear to be getting continued support.

We intend to continue forking from and contributing to https://github.com/BSData/wh40k-apocalypse to help fix issues with the existing datasheets.

At this point, we have added all the new units from the Space Marine codex, and are working on more. We have been recording our reasoning for each datasheet here so it can be discussed and improved by the community, as well:

https://github.com/normanthesquid/wh40k-fundapocalypse/wiki

As far as the name goes, we have been calling it Fundapocalypse, but I understand that that might not be the best name for the community at large. If another name would be better, we are open to suggestions.

**Comment by amis92** [comment]
@normanthesquid We still refrain from hosting fanmade datafiles (or fanmade extensions) as per #86.


However, we now have a nice guide on how to host your repositories more conveniently so that they're easily accessible to your audience via GitHub. Please give the following page from our wiki a read: https://github.com/BSData/catalogue-development/wiki/Help:-Hosting-repositories
