### ISSUE TITLE
New repo: Damn the torpedos!

### ISSUE THREAD

**Issue by Pipkin90** [BSData/catalogue-development#183]
Hello!

I would like to set up a new repository for Battlescribe!
Indie Naval game called "Damn the torpedos!"

**Comment by amis92** [comment]
@Pipkin90 are you still interested? Sorry it took so long, I haven't looked in here lately. That's the game? https://boardgamegeek.com/boardgame/328/damn-torpedoes

**Comment by Pipkin90** [comment]
@amis92 Hello! Yes, I am still intrested :) But, no, that is not the game. DtT haven't been released yet, but is available through discord.

**Comment by amis92** [comment]
Can you provide a link? I just don't know how to find it.

**Comment by amis92** [comment]
If it's not public yet though, maybe consider creating your own repository first: https://github.com/BSData/catalogue-development/wiki/Help:-Hosting-repositories

Then come back here and we can add it in to our organization.

**Comment by Pipkin90** [comment]
Rulebook: https://www.dropbox.com/sh/c9gyy9rz2gl4oof/AAD1qgUPHm9-NPN9DEYrGwDSa?dl=0

Fleetlists: https://www.dropbox.com/s/029g4c4gn41wl7x/Ship%20catalouge.xlsx?dl=0

**Comment by OftKilted** [comment]
> Rulebook: https://www.dropbox.com/sh/c9gyy9rz2gl4oof/AAD1qgUPHm9-NPN9DEYrGwDSa?dl=0
> 
> Fleetlists: https://www.dropbox.com/s/029g4c4gn41wl7x/Ship%20catalouge.xlsx?dl=0

Please take a look at our issue on Hosting fanmade/alternate/community/[put sth here] rulesets and datafiles #86

We still refrain from hosting fanmade datafiles (or fanmade extensions).

However, we now have a nice guide on how to host your repositories more conveniently so that they're easily accessible to your audience via GitHub. Please give the following page from our wiki a read: https://github.com/BSData/catalogue-development/wiki/Help:-Hosting-repositories
