### ISSUE TITLE
New repo: Deadzone 3rd edition

### ISSUE THREAD

**Issue by KurganFr** [BSData/catalogue-development#185]
I would like to start a new repo for the 3rd edition of Mantic's Deadzone sci-fi skirmish game.

I have already created the base catalogue and the two factions from the starter set (GCPS and Veer-Myn).

Thanks in advance.

**Comment by OftKilted** [comment]
There is already a “Deadzone” repo. 

https://github.com/BSData/deadzone

**Comment by KurganFr** [comment]
> There is already a “Deadzone” repo.
> 
> https://github.com/BSData/deadzone

Is it possible to have a separate repo for third edition so as not to overwrite or get mixed up with the existing second edition files? Alternatively, how would you suggest separating the two editions - naming conventions alone? Subfolders?

Thanks.

**Comment by OftKilted** [comment]
I recommend creating an entirely new GST with a new guid, and ensure that your data files also have new guids as well. That allows multiple editions to be in the same repo without running into issues. The WHFB repo is similar in that it has multiple editions in the same repo. 

The gst and data files are named so that catalog creators can differentiate the releases.

**Comment by KurganFr** [comment]
Awesome! I can do that. Thanks for your help!

**Comment by KurganFr** [comment]
After 4 days, I am still waiting for access to the Deadzone repo. Would it be possible to create a separate deadzone-3rd-edition repo after all? Thanks again.

**Comment by OftKilted** [comment]
> After 4 days, I am still waiting for access to the Deadzone repo. Would it be possible to create a separate deadzone-3rd-edition repo after all? Thanks again.

Flagged @amis92 on request to join in https://github.com/BSData/deadzone/issues/54
