### ISSUE TITLE
New repo: Grand Fleet Admiral

### ISSUE THREAD

**Issue by Mackintackin** [BSData/catalogue-development#187]
A Small, Large Fleet Game.

**Comment by OftKilted** [comment]
> A Small, Large Fleet Game.

Please provide more information in reference to the game. (IE Official game URL, Boardgame Geek site etc.)

**Comment by Mackintackin** [comment]
https://legge2.wixsite.com/grandadmiral
https://www.myminifactory.com/users/Grand_Fleet_Admiral_Tabletop
> Grand Fleet Admiral is aiming to be the largest scale fleet on fleet tabletop game on the market, with up to 100 ships or more on the table at any given time.

**Comment by OftKilted** [comment]
> https://legge2.wixsite.com/grandadmiral https://www.myminifactory.com/users/Grand_Fleet_Admiral_Tabletop
> 
> > Grand Fleet Admiral is aiming to be the largest scale fleet on fleet tabletop game on the market, with up to 100 ships or more on the table at any given time.

Bottom line up front would be: “Grand Fleet Admiral” is not a production game, and doesn’t have an available rule set on the website, and rules access requires joining the discord?

**Comment by OftKilted** [comment]
Please take a look at the following issue on fan made games:

Hosting fanmade/alternate/community/[put sth here] rulesets and datafiles 
https://github.com/BSData/catalogue-development/issues/86

We still refrain from hosting fanmade datafiles (or fanmade extensions).

However, we now have a nice guide on how to host your repositories more conveniently so that they're easily accessible to your audience via GitHub. Please give the following page from our wiki a read: https://github.com/BSData/catalogue-development/wiki/Help:-Hosting-repositories

**Comment by Mackintackin** [comment]
> 

alright, thank you.
