### ISSUE TITLE
New repo: 30K Epocalypse

### ISSUE THREAD

**Issue by Bobatar** [BSData/catalogue-development#189]
I'd like to establish a new game system.  Essentially a copy of 40000 Apocalypse but will use 30K era units.  Also, models are AT scale so measurements will be in cm, not inches.

**Comment by OftKilted** [comment]
Please take a look at the following issue on fan made games:

Hosting fanmade/alternate/community/[put sth here] rulesets and datafiles
https://github.com/BSData/catalogue-development/issues/86

We still refrain from hosting fanmade datafiles (or fanmade extensions).

However, we now have a nice guide on how to host your repositories more conveniently so that they're easily accessible to your audience via GitHub. Please give the following page from our wiki a read: https://github.com/BSData/catalogue-development/wiki/Help:-Hosting-repositories

**Comment by Bobatar** [comment]
That works - thanks.
