### ISSUE TITLE
New repo: "Fallout: Wasteland Warfare"

### ISSUE THREAD

**Issue by EnderPal** [BSData/catalogue-development#19]
Can I have the following repository added and be given write access.

**Comment by amis92** [comment]
Hi @EnderPal,

in general, if you want to provide new game system's files, the procedure is as follows:

1. I create new repository for given game system
2. I invite you to that repo
3. You accept the invitation and gain push/write access to that new repo
4. You upload files and maintain them if possible.

The important part is that we Organization Admins do not have time to maintain/push/upload files. So unless there is someone else interested, you'll have to do some work to make our website host those files.

Are you still interested? Should I send you an invite?

Amis

**Comment by EnderPal** [comment]
I am fine with doing all the work.

I made the files last week and have check to make sure that they work and have the correct info.

To answer your question; Yes, I am still interested.

**Comment by amis92** [comment]
Hi @USERNAME,

Please accept the invitation in the email or on the [webpage][invitation]. Welcome aboard!

This is [the new repo][repo].

Don't forget to read through [wiki][], there are some useful guides, especially [Data Author Guide][guide].

**Please read carefully**:
As this is a new repository, please read Data Author Guide linked above very carefully. Save all files in unzipped format (`.cat` instead of `.catz` and `.gst` instead of `.gstz`); you can achieve this using `File`->`Save as` and choosing the correct format from dropdown under filename.
You also shouldn't put any index files (`index.xml` or `index.bsi`), the website on AppSpot does indexing automatically.

Cheers!
Amis

PS You can always `@mention` me by writing `@amis92` in your issue comment, and I'll try to help you out.

[repo]: https://github.com/BSData/fallout-wasteland-warfare
[invitation]: https://github.com/BSData/fallout-wasteland-warfare/invitations
[wiki]: https://github.com/BSData/catalogue-development/wiki
[guide]: https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide
