### ISSUE TITLE
Horus Heresy 2022 needs its own repo

### ISSUE THREAD

**Issue by Mayegelt** [BSData/catalogue-development#190]
It can't be to much longer until the new version of Horus Heresy is released on us.
As such we will need a repo for it.

It seems like there is a large demand for the current one to remain live (and even updated with some more of the player made content).
The new edition based on rather detailed leaks is not backward compatible with the current version. They have revamped a large portion of the movement and assault system as well as profiles and Universal special rules that perviously made up a core of the data in the current one.

**Comment by OftKilted** [comment]
Why create a new repo. Is the current one not functioning?

In alignment with the current guidance and as elaborated by @amis92 

We still refrain from hosting fanmade datafiles (or fanmade extensions).

However, we now have a nice guide on how to host your repositories more conveniently so that they're easily accessible to your audience via GitHub. Please give the following page from our wiki a read: https://github.com/BSData/catalogue-development/wiki/Help:-Hosting-repositories

Interested fans could fork the repo and we could follow the guidance above.

**Comment by Mayegelt** [comment]
The current one works. However the new version of Horus heresy having been taken over by Games-Workshop itself rather than ForgeWorld has dramatic differences to the the way you play stat profiles and everything else.
Back in the not so long ago theough still several years ago Warhammer 40K 7th edition became 8th edition (and now 9th). This also had major changes that meant that it was not backwards compatible with the older version. And as such both sets of data were retained at the time.

It seems from communication with the community that there seems to be quite a lot of people who from the leaks that have been released are not interested in the new edition due to many of the changes. And we'll just wish to continue with the old version, which still requires a few updates and fixes.
This is in part because I am the only person who has been updating the heresy files in the last 2-4 years or so (or at least 99% of it).
In the end we decided to allow some fanmade content to also be hosted as files for the convenience of players as many players in particular regions such as Australia used this player made content and it was widely accepted by a large part of the world wide community, including being allowed at places like Gencon and Adepticon. All of the fan made content that was hosted was of course put behind manual tick boxes and such to prevent it interfering with regular content. So for instance with the mournival rules stuff you needed to click something or load a separate catalogue to access it.

**Comment by Mayegelt** [comment]
In addition to that many people would also like to keep their armies intact but they have saved already.
If there is an overwrite of the existing repo rather than a new repo for it. All those army lists could end up getting wiped due to incompatibility with the new files because as said it is not backwards compatible in any way.
Also at least initially it looks as though not all the current armies will have their own rules. As such you will (as I've had before) end up with ghost files in downloaded versions that no longer function. Not everyone regardless of how many times you tell them to, will delete all data before redownloading the files. I've seen on the 40k one so many times that being said as people end up with multiple versions of an army cat because a new one was made to replace the old one, but it doesn't auto clear files not in the current batch.

It also means ideally I can get some new people who want to add / maintain the new version before it launches, without having an issue of maybe messing up the HH1.0 data. Without such help I don't think the BSData will have a working version before 2023 even though it is guessed release date in May this year

**Comment by Mayegelt** [comment]
In regards to the fanmade content as well. The issue was first bought up on this thread
https://github.com/BSData/horus-heresy/issues/1583 
The one listed as "Ghost" I think was the old senior admin as was "Zopha" and "Alphalas".
In which Amis92 said in regards to the fanmade "As current maintainers of this repository, you make the call."

**Comment by Mayegelt** [comment]
/Bump @OftKilted 
Questions answered, any reply / movement?
I know it's only bee a few days, but wanted to chase this up as I would like progress on it, so it will be able to inform my actions.
As said above I think it better for it to have its own repo. But whether it is best for the current/old one to be remade as the new repo and the new one to overwrite the current. OR to do as said above to just make a new Repo for the new one and leave the old one were it is, but rename it to make clear it is the old version of the game. I do not know.
@amis92 as you were also mentioned, thought you might have thoughts on this as well.

**Comment by OftKilted** [comment]
> In regards to the fanmade content as well. The issue was first bought up on this thread
> [BSData/horus-heresy#1583](https://github.com/BSData/horus-heresy/issues/1583)
> The one listed as "Ghost" I think was the old senior admin as was "Zopha" and "Alphalas".
> In which Amis92 said in regards to the fanmade "As current maintainers of this repository, you make the call."

Two items:
It is possible to have multiple “incompatible versions” of a catalog in a single repo.

They would require a different .gst for each version in the repo. EG a gst for the old edition, and one for the new edition. 

If having multiple editions in the single repo would be too complicated then in keeping consistent policy (which changed after the ticket link provided) It would be best practice to fork the current Horus heresy repo at the point where the “version changes”, and then host the (now community/fan content) using the guidance from the issue here:
https://github.com/BSData/catalogue-development/issues/86

Much like what is done with the current AoS repo. At each release they release a “final version” before jumping to the new edition.

As the code base for that forked release is identical before and after the “forking decision point” users would still be able to use their old lists.

And we work to include that “unofficial/official fork” using issue #86 guidance to assist with user content discovery.

The Volunteer catalog team would then move forward with the new content for the 2022 (?) release.

**Comment by Mayegelt** [comment]
The 2 would need to remain separate I think as the army names would be the same and believe that having a 2nd GST would still give the options of opening the same catalogues (which would change).
The new 2022 version will be being updated. But I think the old one will also receive updates as things are still broken or incomplete in there (including official rules), bit as I'm only 1 person, I can't do everything (or at least haven't as yet).

I am unsure how you would then do a /release for the fork if it got uodates, if that is where the old version ends up residing.

**Comment by OftKilted** [comment]
> The 2 would need to remain separate I think as the army names would be the same and believe that having a 2nd GST would still give the options of opening the same catalogues (which would change). The new 2022 version will be being updated. But I think the old one will also receive updates as things are still broken or incomplete in there (including official rules), bit as I'm only 1 person, I can't do everything (or at least haven't as yet).
> 
> I am unsure how you would then do a /release for the fork if it got uodates, if that is where the old version ends up residing.

If you’re using a completely separate GST (with a separate guid) and the catalogs have completely different guids then having multiple catalogs and core gsts in the same repo isn’t an issue. (The whfb group has been doing that now for a while and they have multiple editions in the same repo.)

**Comment by Mad-Spy** [comment]
As per our conversations on Discord, the new files have been put into the current repo to minimise the hassle of switching over for users.
