### ISSUE TITLE
Request to create a repository for a game system: Test of Honour

### ISSUE THREAD

**Issue by ragados** [BSData/catalogue-development#20]
First version of Test of Honour files are ready for submit. O Great Admins - can I have a repo for these files ;-)

Cheers
Dev

**Comment by amis92** [comment]
Hi @ragados,

Please accept the invitation in the email or on the [webpage][invitation]. Welcome aboard!

In general, if you want to provide new game system's files, the procedure is as follows:
1. I create new repository for given game system: [repo][]
2. I invite you to our organization
3. You accept the [invitation][] and gain push/write access to this new repository
4. You upload files and maintain them if possible.

The important part is that we Organization Admins do not have time to maintain/push/upload files. So unless there is someone else interested, you'll have to do some work to make our website host those files.

Don't forget to read through [wiki][], there are some useful guides, especially [Data Author Guide][guide].

**Please read carefully**:
As this is a new repository, please read Data Author Guide linked above very carefully. Save all files in unzipped format (`.cat` instead of `.catz` and `.gst` instead of `.gstz`); you can achieve this using `File`->`Save as` and choosing the correct format from dropdown under filename.
You also shouldn't put any index files (`index.xml` or `index.bsi`), the website on AppSpot does indexing automatically.

Cheers!
Amis

PS You can always `@mention` me by writing `@amis92` in your issue comment, and I'll try to help you out.

[repo]: https://github.com/BSData/test-of-honour
[invitation]: https://github.com/BSData/test-of-honour/invitations
[wiki]: https://github.com/BSData/catalogue-development/wiki
[guide]: https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide

**Comment by amis92** [comment]
It'd be nice if you gave a link to this game somewhere.

**Comment by ragados** [comment]
https://store.warlordgames.com/collections/test-of-honour
As we had discussed creating the game a few weeks ago I didn't realise you'd need it. I have also included in readme.
I will work on Wiki tonight.
