### ISSUE TITLE
Man O' War

### ISSUE THREAD

**Issue by Skarogne** [BSData/catalogue-development#203]
### Reference contact

@Mad_Spy

### Your Discord

Warhaman

### Additional information

Hi,
We would like to make BattleScribe for Warhammer : Man O' War in English and in French. 
What do you need to know in order to permit us to do that?

Is could be possible to me to add new member for this repository ?

Thanks

**Comment by amis92** [comment]
I'd suggest starting with developing the datafiles in your personal repositories, and after you have some working data, come back to us to request a place in this organization.

From #86 - [...] we have a nice guide on how to host your repositories more conveniently so that they're easily accessible to your audience via GitHub. Please give the following page from our wiki a read: https://github.com/BSData/catalogue-development/wiki/Help:-Hosting-repositories

Also, this might be helpful: https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide

**Comment by Skarogne** [comment]
Thank you for all these explanations
