### ISSUE TITLE
New repo Kill Zone

### ISSUE THREAD

**Issue by mrvitriol** [BSData/catalogue-development#29]
Hi,
I created everything for an old tabletop and would like to include it into BS.
How may I do this?

**Comment by mrvitriol** [comment]
It's some time now, how about a reply? 😊😉

**Comment by amis92** [comment]
Hi, sorry for no response. Can you share these files somewhere (either attach to an issue or push to a repo) so I can see what're we talking about? :)

**Comment by mrvitriol** [comment]
Hi, thanks for the response :-)
I created a kill_zone repo here on github, you can find it at: mrvitriol/kill_zone
I am also working on the next project - a different tabletop from around the same era :-)

**Comment by amis92** [comment]
Hi @mrvitriol,

Please accept the invitation in the email or on the [webpage][invitation]. Welcome aboard!

In general, if you want to provide new game system's files, the procedure is as follows:
1. I create new repository for given game system: [repo][]
2. I invite you to our organization
3. You accept the [invitation][] and gain push/write access to this new repository
4. You upload files and maintain them if possible.

The important part is that we Organization Admins do not have time to maintain/push/upload files. So unless there is someone else interested, you'll have to do some work to make our website host those files.

Don't forget to read through [wiki][], there are some useful guides, especially [Data Author Guide][guide].

**Please read carefully**:
As this is a new repository, please read Data Author Guide linked above very carefully. I've looked at your repo you've linked - there are some differences you need to make for this one: save all files in unzipped format (`.cat` instead of `.catz` and `.gst` instead of `.gstz`); you can achieve this using `File`->`Save as` and choosing the correct format from dropdown under filename.
You also shouldn't put any index files (`index.xml` or `index.bsi`), the website on AppSpot does indexing automatically.

Also you may join our Wh40k team in Gitter chat room (GitHub login): [![Join the chat at Gitter][gitter-badge]][gitter] - it's very active and you can ask for some datafile-oriented help if needed.

Cheers!
Amis

PS You can always `@mention` me by writing `@amis92` in your issue comment, and I'll try to help you out.

[repo]: https://github.com/BSData/killzone
[invitation]: https://github.com/BSData/killzone/invitations
[wiki]: https://github.com/BSData/catalogue-development/wiki
[guide]: https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide
[gitter-badge]: https://badges.gitter.im/Join%20Chat.svg
[gitter]: https://gitter.im/BSData/wh40k?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by amis92** [comment]
I've added a new (8.) bullet point to answer that question since it comes up pretty often: https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide#how-to-release
