### ISSUE TITLE
Updating releases with build artifacts

### ISSUE THREAD

**Issue by Zhaph** [BSData/catalogue-development#30]
We've just released our first build of Middle-Earth, and it's all appearing nicely in the AppSpot listing and within BattleScribe.

I'd like to have the `.bsi` and `.bsr` artifacts added to our releases page in a similar way to Kill Team and 40k:

![image](https://user-images.githubusercontent.com/1271482/48548611-51994280-e8c5-11e8-9a17-5e0e7b8226c3.png)

Obviously I could do it manually once the build has been created, but it looks like this is being done automatically via the build scripts in here - is that as simple as adding an appropriately updated version of the `.appveyor.yml` to our root like them, or is that something only major systems should really use?

**Comment by amis92** [comment]
It's opt-in for everyone.

Essentially, you need to add the configured `.appveyor.yml` file to the repo and ask me to "turn it on" for that repo in AppVeyor (to which only I have access currently) - as you did here. Let me know when you have the file on master branch, and I'll proceed with switching it on!

PS. It won't update already existing releases since it triggers when you create a new one. :)

**Comment by Zhaph** [comment]
Many thanks for confirming @amis92 - I believe I've done that successfully (I think the only setting to change was to uncomment and set the Gitter hook?).

Wasn't expecting a retroactive update, but it's great to have them going forward.

**Comment by amis92** [comment]
Yes, Releases are manually as normal.

Done! The little green tick links to the build.

![image](https://user-images.githubusercontent.com/2671396/48717280-5c333f00-ec19-11e8-819b-7492d4cdd70d.png)

**Comment by Zhaph** [comment]
Many thanks @amis92 :)
