### ISSUE TITLE
New repo: X-wing 2.0

### ISSUE THREAD

**Issue by Starkman9000** [BSData/catalogue-development#31]
I would like to add a new repo for FFGs Star Wars X-wing Second Edition. I have the core set converted already and will be working on the rest throughout the week.

Regards.

**Comment by amis92** [comment]
I'm reluctant to creating new repository. For all the reasons I've mentioned previously (and others), 8th ed for 40k was an exception. Which won't happen again.

If you've created a new game system from scratch (so that the game system ID is different), there will not be any problem with the people that already have the old datafiles. They'll just download new files besides the old ones. The old files won't be easily available (through AppSpot/BattleScribe interface), but that's not really an issue, is it? For those that care, you can provide a link as we did in 40k.

It'd be a good idea to have the `2nd ed.` in the game system name, so it's visible immediately and doesn't clash internally in BattleScribe with old rosters.

**Comment by XWingDrLucky** [comment]
Oh yeah, that makes sense.  I'll do that tonight.  That works.

However, while we are on the subject, can a repo name be edited?  It's always bugged me that the name for the X-Wing repository lacks a colon (Star Wars X-Wing), so it isn't formatted the same as Fantasy Flight's other Star Wars games (Star Wars: Armada and Star Wars: Legion).  If it is possible to edit the name of the X-Wing repo to add the colon (without changing the url or anything)?  If not, no big deal.

**Comment by amis92** [comment]
Yeah, you can edit it, no breaking changes there. There's an "edit" button nearby.


While you're changing up things, could you fix up README formatting? You can use the updated [template](https://github.com/BSData/catalogue-development/wiki/Data-Admin-Guide#create-readme) or just fix manually.

**Comment by amis92** [comment]
on the repo's main GitHub page, on the far right to the repo title, you should have "Edit" button.
