### ISSUE TITLE
New repo: WHFB 6th ed.

### ISSUE THREAD

**Issue by Profi90** [BSData/catalogue-development#32]
Hi! I want to create data files for BS's Warhammer Fantasy Battles 6th ed. Our WFB 6 community is growing bigger in Poland so we need to make rosters... fast using BS :)

**Comment by amis92** [comment]
Hi @Profi90,

Please accept the invitation in the email or on the [webpage][invitation]. Welcome aboard!

In general, if you want to provide new game system's files, the procedure is as follows:
1. I create new repository for given game system: [repo][]
2. I invite you to our organization
3. You accept the [invitation][] and gain push/write access to this new repository
4. You upload files and maintain them if possible.

The important part is that we Organization Admins do not have time to maintain/push/upload files. So unless there is someone else interested, you'll have to do some work to make our website host those files.

Don't forget to read through [wiki][], there are some useful guides, especially [Data Author Guide][guide].

**Please read carefully**:
As this is a new repository, please read Data Author Guide linked above very carefully. I've looked at your repo you've linked - there are some differences you need to make for this one: save all files in unzipped format (`.cat` instead of `.catz` and `.gst` instead of `.gstz`); you can achieve this using `File`->`Save as` and choosing the correct format from dropdown under filename.
You also shouldn't put any index files (`index.xml` or `index.bsi`), the website on AppSpot does indexing automatically.

Also you may join our Wh40k team in Gitter chat room (GitHub login): [![Join the chat at Gitter][gitter-badge]][gitter] - it's very active and you can ask for some datafile-oriented help if needed.

Cheers!
Amis

PS You can always `@mention` me by writing `@amis92` in your issue comment, and I'll try to help you out.

[repo]: https://github.com/BSData/whfb-6th-edition
[invitation]: https://github.com/BSData/whfb-6th-edition/invitations
[wiki]: https://github.com/BSData/catalogue-development/wiki
[guide]: https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide
[gitter-badge]: https://badges.gitter.im/Join%20Chat.svg
[gitter]: https://gitter.im/BSData/wh40k?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by amis92** [comment]
Repository deleted because the files were only a copy of 8th ed https://github.com/BSData/whfb-6th-edition/
