### ISSUE TITLE
New repo: Kings of War - Vanguard

### ISSUE THREAD

**Issue by BitPsycho** [BSData/catalogue-development#35]
Hi there,

I would like to open a new repo for 'Kings of War - Vanguard'.

Thanks :-)

**Comment by Mautibusu** [comment]
I have worked on adding a few bands to the work @BitPsycho started, and can attest that it is of very good quality, so for what it's worth, I highly support the creation of this repo!

**Comment by amis92** [comment]
Hi @BitPsycho,

Please accept the invitation in the email or on the [webpage][invitation]. Welcome aboard!

In general, if you want to provide new game system's files, the procedure is as follows:
1. I create new repository for given game system: [repo][]
2. I invite you to our organization
3. You accept the [invitation][] and gain push/write access to this new repository
4. You upload files and maintain them if possible.

The important part is that we Organization Admins do not have time to maintain/push/upload files. So unless there is someone else interested, you'll have to do some work to make our website host those files.

Don't forget to read through [wiki][], there are some useful guides, especially [Data Author Guide][guide].

**Please read carefully**:
As this is a new repository, please read Data Author Guide linked above very carefully. I've looked at your repo you've linked - there are some differences you need to make for this one: save all files in unzipped format (`.cat` instead of `.catz` and `.gst` instead of `.gstz`); you can achieve this using `File`->`Save as` and choosing the correct format from dropdown under filename.
You also shouldn't put any index files (`index.xml` or `index.bsi`), the website on AppSpot does indexing automatically.

Cheers!
Amis

PS You can always `@mention` me by writing `@amis92` in your issue comment, and I'll try to help you out.

[repo]: https://github.com/BSData/kings-of-war-vanguard
[invitation]: https://github.com/BSData/kings-of-war-vanguard/invitations
[wiki]: https://github.com/BSData/catalogue-development/wiki
[guide]: https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide

**Comment by BitPsycho** [comment]
Thanks Amis92 :-)

Just a question about the repo ... We already started a GitHub project while waiting for this one to become active.  Is there a way to link our repo with this one so they automatically sync ?  Or is there a better way to work that you would recommend ?

Thx

**Comment by amis92** [comment]
You'll need to move your files over to the new repo, no way to link repos. You just have to use the new one directly.
