### ISSUE TITLE
New repo: Add new Game Freebooter´s Fate #2

### ISSUE THREAD

**Issue by Kuinasan** [BSData/catalogue-development#44]
Hello, I have written a new game data for battlescribe, I would like to upload it so everyone can use it. What do I have to do for it? It is Freebooter´s Fate #2.

**Comment by Kuinasan** [comment]
Hello, I wanted to ask how far the new repo, I have a couple of people who want to know when the game comes online
Sincerely, Kuina

**Comment by amis92** [comment]
@Kuinasan hello, sorry for the long wait.

Please accept the invitation in the email or on the [webpage][invitation]. Welcome aboard!

In general, if you want to provide new game system's files, the procedure is as follows:
1. I create new repository for given game system: [repo][]
2. I invite you to our organization
3. You accept the [invitation][] and gain push/write access to this new repository
4. You upload files and maintain them if possible.

The important part is that we Organization Admins do not have time to maintain/push/upload files.
Don't forget to read through [wiki][], there are some useful guides, especially [Data Author Guide][guide].

**Please read carefully**:
As this is a new repository, please read Data Author Guide linked above very carefully. Save all files in unzipped format (`.cat` instead of `.catz` and `.gst` instead of `.gstz`); you can achieve this using `File`->`Save as` and choosing the correct format from dropdown under filename.
You also shouldn't put any index files (`index.xml` or `index.bsi`), the website on AppSpot does indexing automatically.

Cheers!
Amis

PS You can always `@mention` me by writing `@amis92` in your issue comment, and I'll try to help you out.

[repo]: https://github.com/BSData/freebooters-fate
[invitation]: https://github.com/BSData/freebooters-fate/invitations
[wiki]: https://github.com/BSData/catalogue-development/wiki
[guide]: https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide
