### ISSUE TITLE
New repository for the Warhammer Armies Project

### ISSUE THREAD

**Issue by L3610N115** [BSData/catalogue-development#45]
Good day. I am making files for the Warhammer Armies Project http://warhammerarmiesproject.blogspot.com/

To make my files publicly available I have to host them somewhere and then use the dataindexer if I am not mistaken. I wanted to ask where people host their files. The tutorial video mentions Dropbox but Dropbox does no longer offer public folders.

**Comment by amis92** [comment]
Hi @L3610N115,

Please accept the invitation in the email or on the [webpage][invitation]. Welcome aboard!

In general, if you want to provide new game system's files, the procedure is as follows:
1. I create new repository for given game system: [repo][]
2. I invite you to our organization
3. You accept the [invitation][] and gain push/write access to this new repository
4. You upload files and maintain them if possible.

The important part is that we Organization Admins do not have time to maintain/push/upload files. So unless there is someone else interested, you'll have to do some work to make our website host those files.

Don't forget to read through [wiki][], there are some useful guides, especially [Data Author Guide][guide].

**Please read carefully**:
As this is a new repository, please read Data Author Guide linked above very carefully. Save all files in unzipped format (`.cat` instead of `.catz` and `.gst` instead of `.gstz`); you can achieve this using `File`->`Save as` and choosing the correct format from dropdown under filename.
You also shouldn't put any index files (`index.xml` or `index.bsi`), the website on AppSpot does indexing automatically.

Cheers!
Amis

PS You can always `@mention` me by writing `@amis92` in your issue comment, and I'll try to help you out.

[repo]: https://github.com/BSData/warhammer-armies-project
[invitation]: https://github.com/BSData/warhammer-armies-project/invitations
[wiki]: https://github.com/BSData/catalogue-development/wiki
[guide]: https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide
