### ISSUE TITLE
New repo: Bushido

### ISSUE THREAD

**Issue by Fleafa** [BSData/catalogue-development#66]
Hi. I would like you to host my Bushido repository.
I previously created a repo for the public beta rules. Now the new edition is out, I am in the process of revising the structure and would like to make it widely available.

**Comment by amis92** [comment]
Hi @Fleafa ,

This is the new repository: https://github.com/BSData/bushido . Since you're a member already, I've assigned write access to you.

Don't forget to read through [wiki][], there are some useful guides, especially [Data Author Guide][guide].

**Please read carefully**:
As this is a new repository, please read Data Author Guide linked above very carefully.

Also, join the data author community over at discord!

[![Chat on Discord](https://img.shields.io/discord/558412685981777922.svg?logo=discord&style=popout-square)](https://discord.gg/KqPVhds)

Cheers!
Amis

PS You can always `@mention` me by writing `@amis92` in your issue comment, and I'll try to help you out.

[repo]: https://github.com/BSData/bushido
[invitation]: https://github.com/BSData/bushido
[wiki]: https://github.com/BSData/catalogue-development/wiki
[guide]: https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide
