### ISSUE TITLE
Last Days: Zombie Apocalypse

### ISSUE THREAD

**Issue by andreanespeca** [BSData/catalogue-development#73]
Hi Guys not a super program developer here i have done few things in the past but first time with github. I have ready a data file already working for a new game a like called Last day Zombie apocalypse with rulebook published by Osprey games. I would like to share it with the community what should i do in easy step? Thanks
Andrea

**Comment by andreanespeca** [comment]
Sorry if i ask but as said not familiar with Github, is it created or is it in the process of being created? Thanks for your help.

Andrea

**Comment by amis92** [comment]
In the process. Which effectively means it's on my todo list and I have to get myself and do it at some point.

**Comment by amis92** [comment]
Hi @andreanespeca,

Please accept the invitation in the email or on the [webpage][invitation]. Welcome aboard!

In general, if you want to provide new game system's files, the procedure is as follows:
1. I create new repository for given game system: [repo][]
2. I invite you to the repo
3. You accept the [invitation][] and gain push/write access to this new repository
4. You upload files and maintain them if possible.

The important part is that we Organization Admins do not have time to maintain/push/upload files. So unless there is someone else interested, you'll have to do some work to make our website host those files.

Don't forget to read through [wiki][], there are some useful guides, especially [Data Author Guide][guide].

**Please read carefully**:
As this is a new repository, please read Data Author Guide linked above very carefully. Save all files in unzipped format (`.cat` instead of `.catz` and `.gst` instead of `.gstz`); you can achieve this using `File`->`Save as` and choosing the correct format from dropdown under filename.
You also shouldn't put any index files (`index.xml` or `index.bsi`), the website on AppSpot does indexing automatically.

Also, join the data author community over at discord!

[![Chat on Discord](https://img.shields.io/discord/558412685981777922.svg?logo=discord&style=popout-square)](https://discord.gg/KqPVhds)

Cheers!
Amis

PS You can always `@mention` me by writing `@amis92` in your issue comment, and I'll try to help you out.

[repo]: https://github.com/BSData/last-days-zombie-apocalypse
[invitation]: https://github.com/BSData/last-days-zombie-apocalypse/invitations
[wiki]: https://github.com/BSData/catalogue-development/wiki
[guide]: https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide
