### ISSUE TITLE
Need some Help on a condition

### ISSUE THREAD

**Issue by KealL** [BSData/catalogue-development#94]
So Veteran Adds 20%, then roundes to the nearest 10.

So a 110 pts unit made veteran becomes 140pts (110+ 20% round (132 up to 140))
Similarly Inexperience deducts 20% then rounds up. 110pts made inexperienced becomes (110-20% round (88 up to 90).
I've put in the following;
![image](https://user-images.githubusercontent.com/14986801/73788715-72350d00-4795-11ea-81fe-49b6a7415064.png)

The rule is set to model points and the crew are set as upgrades.
And it does not seem to always recalc the points

![image](https://user-images.githubusercontent.com/14986801/73788814-9f81bb00-4795-11ea-9e83-1dcb6847b873.png)

![image](https://user-images.githubusercontent.com/14986801/73788856-ae686d80-4795-11ea-991f-02c135742b05.png)

![image](https://user-images.githubusercontent.com/14986801/73788873-b6c0a880-4795-11ea-9d84-5f69b2b997c9.png)

![image](https://user-images.githubusercontent.com/14986801/73788946-d9eb5800-4795-11ea-91d0-9360b8308ddb.png)

![image](https://user-images.githubusercontent.com/14986801/73789024-f4bdcc80-4795-11ea-9711-7292fd3588b7.png)

How do I fix this?

**Comment by DarkSkyT9A** [comment]
Multiple issues I can spot with this implementation.

* First your modifier subtracts 10 points for every fifty points. I assume you wanted it to round, but that doesn't work. Examples: Your cost is 225, you'd now subtract 40 points, when you want 22.5. You need to increase 10 points for every 100 points. Then solve the rounding afterwards. I do believe instead of setting straight numbers you should be able to send a percentage as well.
* If the game system does actually not use any points beyond multiplies of 10, you can just ignore everything single digit (this is actually an "error" in the game, though).
* Another workaround could be to create different modifiers (e.g. each update costs differently based on Crew) or even base entries for the ships (i.e. Ship with Normal Crew, Ship with Experienced Crew, Ship with Unexperienced Crew). These may not be particularly nice, but will do the job easily.

**Comment by DrTobogganMD** [comment]
If you still have issues, please visit us on github - this repo is for the request of new catalogues.
